### ISSUE TITLE
having problems connecting to nodes

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-mobile-wallet#124] opened 2021-02-08 21:45 UTC
**Steps to reproduce**
open iOS app, try to use it

**Current behavior**
anytime I try to switch accounts I get a message in red saying the app can't connect to a node.  sometimes it eventually does and sometimes doesn't. 

**Expected behavior**
for the app to connect to a node and get my balance. 
 
**Affected Version**
Version 4 (12)

**Screenshots**
![IMG_5008](https://user-images.githubusercontent.com/10395907/107285357-68438b00-6a35-11eb-85b1-0b8ae5015c6d.PNG)

**Comment by Peersyst** [comment] 2021-02-15 16:08
Duplicate of #128

**Closed by Peersyst** 2021-02-15 16:08 UTC
